version: '3.8'

services:
  postgres:
    image: postgres:16-bullseye
    container_name: postgres16_container
    env_file: .env
    environment:
      POSTGRES_DB: ${DATABASE}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - postgres16_network
    ports:
      - "5433:${PORT}"

  dvf:
    build: .
    container_name: dvf_container
    env_file: .env
    ports:
      - "8008:8000"
    networks:
      - postgres16_network

networks:
  postgres16_network:
    driver: bridge

volumes:
  pgdata: